timer: add missing includes
Fixes following build errors:

 timer.h:7:2: error: unknown type name ‘bool’
 timer.h:12:19: error: field ‘list’ has incomplete type

Signed-off-by: Petr Štetiar <ynezz@true.cz>